config/routes.rb
Rails.application.routes.draw do
  
  resources :restaurants do
    resources :reservations
  end
  
  devise_for :users

  root 'restaurants#index'

end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :restaurants

  USER_ROLES = ["regular", "admin"]
  private_constant :USER_ROLES

  validates_inclusion_of :role, in: USER_ROLES

  def admin?
  	role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

before_action :get_restaurant

def index
	@reservation = Reservation.all
end

def new
    @reservation = @restaurant.reservations.new
end

def create
	#What is this, here? And why doesn't it follow the same @restaurant.reservations format, above?
	@reservation = Reservation.new(reservation_params)
	if @reservation.save
		#We'll want to add a line here: ReservationMailer.confirm_email(@restaurant.user).deliver
		flash[:success] = "Congrats! Reservation number #{@reservation.id} created!"
		#In Ruby, what does the below mean? And what's the difference between that and render?
		#We have a hash down below because the we're passing parameters instead of just specifying a path
		redirect_to restaurant_reservation_path(restaurant_id: @reservation.restaurant.id, id: @reservation.id)
	else
		render 'new'
	end
end

def show
	@reservation = @restaurant.reservations.find(params[:id])
	if @reservation
      render :show
    else
      flash[:warning] = "Sorry! That reservation doesn't exist."
      redirect_to new_restaurant_reservation_path
    end
end

def edit
	@reservation = @restaurant.reservations.find(params[:id])
end

def update
	@reservation = @restaurant.reservations.find(params[:id])
	if @restaurant.reservations.update(reservation_params)
		redirect_to restaurant_reservation_path
	else
		render 'edit'
	end
end

def destroy
	@reservation = @restaurant.reservations.find(params[:id])
		if @reservation.destroy
			flash[:danger] = "Reservation was successfully deleted."
			redirect_to restaurants_path
		else 
			flash[:danger] = "Reservation was not deleted! Give us a call, and we'll do this the old-fashioned way."
			redirect_to restaurant_path(restaurant_id: @reservation.restaurant.id)
		end
end



# def destroy
# 	@restaurant=current_user.restaurants.find(params[:id])
# 	if @restaurant.destroy
# 		flash[:danger] = "Restaurant was successfully deleted."
# 		redirect_to restaurants_path
# 	else
# 		flash[:danger] = "Restaurant was not deleted!"
# 		redirect_to restaurants_path
# 	end
# end




	private

def reservation_params
	params.require(:reservation).permit(:email, :restaurant_id, :reserve_time, :reserve_date, :message)
end

def get_restaurant
	@restaurant = Restaurant.find(params[:restaurant_id])
end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

before_action :authenticate_user!, except: [:show,:index]

#before_action :set_restaurant, only: [:show]

def index
	@restaurant = Restaurant.all
end

def new
	@restaurant = current_user.restaurants.new
end

def create
	@restaurant = current_user.restaurants.new(restaurant_params)
	if @restaurant.save
		flash[:success] = "Restaurant was successfully created."
	  	redirect_to restaurant_path(@restaurant)
	else
	render 'new'
	end
end

def show
	@restaurant = Restaurant.find(params[:id])
end

def edit
	@restaurant = current_user.restaurants.find(params[:id])	
end

def update
	@restaurant=current_user.restaurants.find(params[:id])
	if @restaurant.update(restaurant_params)
		flash[:success] = "Restaurant was successfully updated."
		redirect_to restaurant_path(@restaurant)
	else 
		render 'edit'
	end
end

def destroy
	@restaurant=current_user.restaurants.find(params[:id])
	if @restaurant.destroy
		flash[:danger] = "Restaurant was successfully deleted."
		redirect_to restaurants_path
	else
		flash[:danger] = "Restaurant was not deleted!"
		redirect_to restaurants_path
	end
end

  private

  def restaurant_params
  	params.require(:restaurant).permit(:name, :description, :address, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reservester</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
Logged in as <strong><%= current_user.email %></strong>.
<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-
link' %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for [@restaurant, @reservation] do |f| %>
	<% if @reservation.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
		<ul>
			<% @reservation.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

<p>
	<%= f.label :email %><br>
	<%= f.text_field :email %>
</p>
<p>
	<%= f.label :reserve_date %><br>
	<%= f.text_field :reserve_date %>
</p>
<p>
	<%= f.label :reserve_time %><br>
	<%= f.text_field :reserve_time %>
</p>
<p>
	<%= f.label :message %><br>
	<%= f.text_field :message %>
</p>
<p>
	<%=f.hidden_field :restaurant_id, value: @restaurant.id %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>
<br>
<%= flash[:warning] %>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservation Director</h1>
<b><%= "Here are the reservations for #{@restaurant.name}:"%></b>
<br>
<br>
<table>
  <tr>
    <th>Email</th>
    <th>Reserve Date</th>
    <th>Reserve Time</th>
    <th>Message</th>
  </tr>

<% @restaurant.reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.email %></td>
    <td><%= reservation.reserve_date %></td>
    <td><%= reservation.reserve_time %></td>
    <td><%= reservation.message %></td>
  </tr>
<% end %>
</table>

<%= link_to "Home", restaurants_path%>

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/reservations/show.html.erb
<h1>Reservations</h1>
    <br><br>

     <th><b>Email:</b></th> <%= @reservation.email %> <br>
     <th><b>Message:</b></th> <%= @reservation.message %><br>
     <th><b>Time:</b></th> <%= @reservation.reserve_time %><br>
     <th><b>Date:</b></th> <%= @reservation.reserve_date %>
	<br><br>
     <th><%= link_to 'Home', root_path %></th>
   </div>
 </div>
 <br>
<%= flash[:success] %>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<% if @restaurant.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>
		<ul>
		<% @restaurant.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
		</div>
	<% end %>

<p>
	<%= f.label :name %><br>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :description %><br>
	<%= f.text_area :description %>
</p>
<p>
	<%= f.label :address %><br>
	<%= f.text_field :address %>
</p>
<p>
	<%= f.label :phone %><br>
	<%= f.text_field :phone %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>
<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurant Directory</h1>
<br>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Address</th>
    <th>Phone Number</th>
  </tr>
 
<% @restaurant.each do |restaurant| %>
  <tr>
    <td><%= restaurant.name %></td>
    <td><%= restaurant.description %></td>
    <td><%= restaurant.address %></td>
    <td><%= restaurant.phone %></td>
    <td><%= link_to "Open", restaurant_path(restaurant) %></td>
  </tr>
<% end %>
</table>
 

<br>
 
<%= link_to "Create New Restaurant", new_restaurant_path %>
<br>
<%= flash[:danger] %>

app/views/restaurants/new.html.erb
<h1>Enter a New Restaurant</h1>
<%= render 'form' %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p>
<strong>Name:</strong>
<%= @restaurant.name %>
</p>
<p>
<strong>Description:</strong>
<%= @restaurant.description %>
</p>
<p>
<strong>Address:</strong>
<%= @restaurant.address %>
</p>
<p>
<strong>Phone:</strong>
<%= @restaurant.phone %>
</p>
<% if @restaurant.user_id == current_user.id %>
	<%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
	<%= link_to 'Delete', restaurant_path(@restaurant), method: :delete %>
<% end %>
<%= link_to 'Back', restaurants_path %>
<p>
<strong>User:</strong>
<%= @restaurant.user.email %>
</p>
<br>

<iframe

src="https://www.google.com/maps/embed/v1/place?key=AIzaSyD5nt-kaFLNPJ4eifWEBOKyplZFE35MZ6E

&q=<%= @restaurant.address %>">

</iframe>

<br>
<%= link_to "Create New Reservation", new_restaurant_reservation_path(@restaurant)%>
<br>

<% if @restaurant.user_id == current_user.id %>
	<%= link_to "View Reservations for this Restaurant", restaurant_reservations_path(@restaurant)%>
<% end %>
<br>
<%= flash[:success] %>